main:
  - local-path: "/home"
    url: "/"
  - local-path: "/about"
    url: "/about"
  - local-path: "/pages"
    url: "/pages"
    children:
      - local-path: "/pages/legal"
        url: "/pages/legal"
  - local-path: "/docs"
    url: "/docs"
    children:
      - local-path: "/docs/getting-started"
        url: "/docs/getting-started"
      - local-path: "/docs/api"
        url: "/docs/api"
  - local-path: "/blog"
    url: "/blog"
  - local-path: "/shop"
    url: "/shop"

