main:
  - url: "/"
    title: Home
  - url: "/about"
    title: About
  - url: "/pages"
    title: Pages
    children:
      - url: "/pages/legal"
        title: Legal
  - url: "/docs"
    title: Docs
    children:
      - url: "/docs/getting-started"
        title: Getting Started
      - url: "/docs/api"
        title: API
  - url: "/blog"
    title: Blog
  - url: "/shop"
    title: Shop

