main:
  - url: "/docs/api"
    title: API
    children:
      - url: "/docs/api/authentication"
        title: Authentication
      - url: "/docs/api/endpoints"
        title: Endpoints
  - url: "/docs/getting-started"
    title: Getting Started
    children:
      - url: "/docs/getting-started/introduction"
        title: Introduction
      - url: "/docs/getting-started/quickstart"
        title: Quick Start
      - url: "/docs/getting-started/installation"
        title: Installation
  - url: "/docs/core-concepts"
    title: Core Concepts
    children:
      - url: "/docs/core-concepts/architecture"
        title: Architecture
      - url: "/docs/core-concepts/components"
        title: Components
      - url: "/docs/core-concepts/styling"
        title: Styling
  - url: "/docs/advanced"
    title: Advanced
    children:
      - url: "/docs/advanced/customization"
        title: Customization
      - url: "/docs/advanced/plugins"
        title: Plugins
      - url: "/docs/advanced/themes"
        title: Themes
  - url: "/docs/reference"
    title: Reference
    children:
      - url: "/docs/reference/api-reference"
        title: API Reference
      - url: "/docs/reference/migration-guide"
        title: Migration Guide
      - url: "/docs/reference/changelog"
        title: Changelog
