main:
  - local-path: "/docs/api"
    url: "/api"
  - local-path: "/getting-started"
    url: "/getting-started"
    children:
      - local-path: "/getting-started/introduction"
        url: "/getting-started/introduction"
      - local-path: "/getting-started/quick-start"
        url: "/getting-started/quick-start"
      - local-path: "/getting-started/installation"
        url: "/getting-started/installation"
  - local-path: "/core-concepts"
    url: "/core-concepts"
    children:
      - local-path: "/core-concepts/architecture"
        url: "/core-concepts/architecture.md"
      - local-path: "/core-concepts/components"
        url: "/core-concepts/components"
      - local-path: "/core-concepts/styling"
        url: "/core-concepts/styling"
  - local-path: "/advanced"
    url: "/advanced"
    children:
      - local-path: "/advanced/customization"
        url: "/advanced/customization"
      - local-path: "/advanced/plugins"
        url: "/advanced/plugins"
      - local-path: "/advanced/themes"
        url: "/advanced/themes"
  - local-path: "/reference"
    url: "/reference"
    children:
      - local-path: "/reference/api-reference"
        url: "/reference/api-reference"
      - local-path: "/reference/migration-guide"
        url: "/reference/migration-guide"
      - local-path: "/reference/changelog"
        url: "/reference/changelog"
