main:
  - local-path: "home"
    url: "/"
  - local-path: "about"
    url: "/about"
  - local-path: "pages"
    url: "/pages"
  - local-path: "docs"
    url: "/docs"
    children:
      - local-path: "getting-started"
        url: "/docs/getting-started"
      - local-path: "api"
        url: "/docs/api"
  - local-path: "blog"
    url: "/blog"
  - local-path: "shop"
    url: "/shop"

